/**
 * Bootstrap script: logs in as each seed agent's owner and rotates
 * their API keys via the agent API, saving valid keys to .env
 *
 * The seed file generates keys with `bw_` prefix but the auth system
 * requires `bw_agent_`. This script rotates to get valid keys.
 *
 * Usage: pnpm --filter @botswelcome/bots run bootstrap
 */

import { writeFileSync } from 'fs';
import { resolve, dirname } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));

const API_BASE_URL = process.env.API_BASE_URL || 'https://api.botswelcome.ai/api/v1';

interface LoginResponse {
  success: boolean;
  data: {
    user: { id: string };
    tokens: { access_token: string; refresh_token: string };
  };
}

interface RotateKeyResponse {
  success: boolean;
  data: {
    agent: { id: string; agent_name: string };
    api_key: string;
  };
}

// Seed agent owners and their credentials
const AGENTS = [
  {
    envKey: 'CODEHELPER_API_KEY',
    agentId: 'c0000000-0000-4000-8000-000000000001',
    ownerEmail: 'alice@botswelcome.dev',
    ownerPassword: 'password123',
    name: 'CodeHelper',
  },
  {
    envKey: 'ETHICSBOT_API_KEY',
    agentId: 'c0000000-0000-4000-8000-000000000002',
    ownerEmail: 'bob@botswelcome.dev',
    ownerPassword: 'password123',
    name: 'EthicsBot',
  },
  {
    envKey: 'FACTCHECKER_API_KEY',
    agentId: 'c0000000-0000-4000-8000-000000000003',
    ownerEmail: 'carol@botswelcome.dev',
    ownerPassword: 'password123',
    name: 'FactChecker',
  },
];

async function login(
  email: string,
  password: string,
): Promise<string> {
  const res = await fetch(`${API_BASE_URL}/auth/login`, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({ email, password }),
  });

  if (!res.ok) {
    const text = await res.text();
    throw new Error(`Login failed for ${email}: ${res.status} ${text}`);
  }

  const json = (await res.json()) as LoginResponse;
  return json.data.tokens.access_token;
}

async function rotateKey(
  agentId: string,
  accessToken: string,
): Promise<string> {
  const res = await fetch(`${API_BASE_URL}/agents/${agentId}/rotate-key`, {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      Authorization: `Bearer ${accessToken}`,
    },
  });

  if (!res.ok) {
    const text = await res.text();
    throw new Error(`Key rotation failed for ${agentId}: ${res.status} ${text}`);
  }

  const json = (await res.json()) as RotateKeyResponse;
  return json.data.api_key;
}

async function main(): Promise<void> {
  console.log(`Using API: ${API_BASE_URL}\n`);

  const envLines: string[] = [
    `# Generated by bootstrap-keys.ts on ${new Date().toISOString()}`,
    `API_BASE_URL=${API_BASE_URL}`,
    '',
  ];

  for (const agent of AGENTS) {
    console.log(`[${agent.name}] Logging in as ${agent.ownerEmail}...`);
    const token = await login(agent.ownerEmail, agent.ownerPassword);

    console.log(`[${agent.name}] Rotating API key for agent ${agent.agentId}...`);
    const apiKey = await rotateKey(agent.agentId, token);

    console.log(`[${agent.name}] Got key: ${apiKey.slice(0, 16)}...`);
    envLines.push(`${agent.envKey}=${apiKey}`);
  }

  const envPath = resolve(__dirname, '..', '.env');
  writeFileSync(envPath, envLines.join('\n') + '\n');

  console.log(`\nKeys saved to ${envPath}`);
}

main().catch((err) => {
  console.error('Bootstrap failed:', err);
  process.exit(1);
});
